import { ApiProvider } from "@/components/providers/api.provider";
import "./globals.css";
import "@whop/frosted-ui/index.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { FrostedProvider } from "@/components/providers/frosted.provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className="max-w-7xl mx-auto p-10 h-screen">
        <ApiProvider>
          <FrostedProvider>{children}</FrostedProvider>
        </ApiProvider>
      </body>
    </html>
  );
}
